import type { Transaction } from "./transactions";
import type { TransactionDecision } from "@/hooks/use-decisions";

export function generateDisputeReport(
  transactions: Transaction[],
  decisions: Map<string, TransactionDecision>
): string {
  const disputed = transactions.filter(
    (tx) => decisions.get(tx.id)?.decision === "dispute"
  );

  if (disputed.length === 0) return "";

  const totalAmount = disputed.reduce((sum, tx) => sum + tx.amount, 0);
  const today = new Date().toLocaleDateString("en-AU", {
    day: "numeric",
    month: "long",
    year: "numeric",
  });

  const lines: string[] = [
    "DISPUTED TRANSACTIONS - STATEMENT REVIEW",
    "=========================================",
    `Date: ${today}`,
    `Total disputed items: ${disputed.length}`,
    `Total disputed amount: $${totalAmount.toFixed(2)}`,
    "",
    "-----------------------------------------",
  ];

  disputed.forEach((tx, i) => {
    const decision = decisions.get(tx.id);
    const reason = decision?.note?.trim() || "(no reason provided)";
    lines.push(`${i + 1}. Date: ${tx.date}`);
    lines.push(`   Description: ${tx.description}`);
    lines.push(`   Amount: $${tx.amount.toFixed(2)}`);
    lines.push(`   Reason: ${reason}`);
    if (i < disputed.length - 1) lines.push("");
  });

  lines.push("-----------------------------------------");
  lines.push("");
  lines.push("Please review and respond to the above");
  lines.push("disputed charges at your earliest convenience.");
  lines.push("");
  lines.push("Generated by SAH Statement Checker");

  return lines.join("\n");
}

export function getDisputedTransactions(
  transactions: Transaction[],
  decisions: Map<string, TransactionDecision>
): Transaction[] {
  return transactions.filter(
    (tx) => decisions.get(tx.id)?.decision === "dispute"
  );
}
